Repository abhimaninnovations/Hactoberfest_2021, pull requests merged in 2021-10, with the labels that each got.

#1 Create hollowdiamond.py
  hollowdiamond.py
Labels: hacktoberfest, hactoberfest_accepted

#3 Java codes
  Java Programs (DSA)/AllIndicesOfNumber.java
  Java Programs (DSA)/ArrayListBasics.java
  Java Programs (DSA)/ArraySum copy.java
  Java Programs (DSA)/CalculatePower.java
  Java Programs (DSA)/CheckNumberInArray.java
  Java Programs (DSA)/CheckSortedArray.java
  Java Programs (DSA)/DeleteRecursiveInLinkedList.java
  Java Programs (DSA)/Factorial.java
  Java Programs (DSA)/FibonacciSeries.java
  Java Programs (DSA)/FirstIndexOfNumber.java
  Java Programs (DSA)/InsertNodeInLL.java
  Java Programs (DSA)/InsertRecursiveInLinkedList.java
  Java Programs (DSA)/LastIndexOfNumber.java
  Java Programs (DSA)/LinkedListBasics.java
  Java Programs (DSA)/MergeSortOnLinkedList.java
  Java Programs (DSA)/MergeTwoSortedLinkedList.java
  Java Programs (DSA)/MidPointOfLinkedList.java
  Java Programs (DSA)/Node copy 2.java
  Java Programs (DSA)/Node copy.java
  Java Programs (DSA)/Node.java
  Java Programs (DSA)/NumberOfDigit.java
  Java Programs (DSA)/PrintNumber.java
  Java Programs (DSA)/PrintRecursivelyLinkedList.java
  Java Programs (DSA)/QueueUse.java
  Java Programs (DSA)/QueueUsingArrays.java
  Java Programs (DSA)/QueueUsingList.java
  Java Programs (DSA)/QueueUsingTwoStacks.java
  Java Programs (DSA)/RemoveConsecutiveDuplicates.java
  Java Programs (DSA)/ReverseLinkedList.java
  Java Programs (DSA)/SumOfNaturalNo.java
  Java Programs (DSA)/TakeInputLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#4 Created File Sorting with CMD Batch
  TypeScript/sort.bat
Labels: hacktoberfest-accepted

#5 DingDong Python Game
  Python Games/DingDong.py
Labels: hacktoberfest-accepted

#6 Java codes
  Snake game in html css js/index.html
Labels: hacktoberfest-accepted

#7 MayaJaal the Maze
  Python Games/MayaJaal.py
Labels: hacktoberfest-accepted

#8 YaadDast the Memory Game
  Python Games/Spinner.py
  Python Games/YaadDast.py
Labels: hacktoberfest-accepted

#9 Java codes
  game 2048/index.html
  game 2048/style.css
Labels: hacktoberfest-accepted

#11 tmp
  Python Games/PyGames/tictactoe.py
  Python Games/PyGames/tmp.py
Labels: hacktoberfest-accepted

#12 tictactoe
  Python Games/PyGames/color.py
  Python Games/PyGames/tictactoe.py
Labels: hacktoberfest-accepted

#13 colorgame
  Python Games/PyGames/colorgame.py
Labels: hacktoberfest-accepted
